CREATE TABLE dfp.tcus_bltn_m (
	bltn_no varchar(20) NOT NULL,
	corp_cd varchar(10) NULL,
	sys_cls_cd varchar(20) NULL,
	bltn_cls_cd varchar(20) NULL,
	pstg_yn varchar(1) NULL,
	up_expsr_yn varchar(1) NULL,
	eml_send_trgt_yn varchar(1) NULL,
	titl varchar(200) NULL,
	contt text NULL,
	atch_file_no varchar(20) NULL,
	tag varchar(500) NULL,
	rmrk varchar(500) NULL,
	eml_send_yn varchar(1) NULL,
	eml_send_ymd date NULL,
	video_webina_typ_cd varchar(20) NULL,
	reprstitv_img_yn varchar(1) NULL,
	thumbnail_img_url varchar(1024) NULL,
	event_begin_dt date NULL,
	event_end_dt date NULL,
	corp_nm varchar(100) NULL,
	corp_logo_url varchar(1024) NULL,
	inpt_usr_id varchar(100) NOT NULL,
	inpt_dtm timestamp NOT NULL,
	updt_usr_id varchar(100) NOT NULL,
	updt_dtm timestamp NOT NULL,
	del_yn varchar(1) DEFAULT 'N'::character varying NULL,
	CONSTRAINT tcus_bltn_m_pk PRIMARY KEY (bltn_no)
);